### ISSUE TITLE
[Bug]: New version has client code executing on server

### ISSUE THREAD

**Issue by tgstyle** [terrarium-earth/Cognition#8]
### Bug Description

Seems the GUI change didn't get set to client only?

### Version

1.4.4

### Mod Loader Version

1.19.2

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by katubug** [comment]
[crash-2023-06-24_19.52.29-fml.txt](https://github.com/terrarium-earth/Experience-Obelisk/files/11858027/crash-2023-06-24_19.52.29-fml.txt)
I'm guessing this is the reason for my server crash?

**Comment by ModernGamingWorld** [comment]
[24.06 20:29:48] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: experienceobelisk, class com.cyanogen.experienceobelisk.ExperienceObelisk
[24.06 20:29:48] [Server] java.lang.reflect.InvocationTargetExceptionnull
[24.06 20:29:48] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[24.06 20:29:48] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[24.06 20:29:48] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[24.06 20:29:48] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[24.06 20:29:48] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[24.06 20:29:48] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.14.jar%23951!/:?] {}
[24.06 20:29:48] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.14.jar%23950!/:?] {}
[24.06 20:29:48] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[24.06 20:29:48] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[24.06 20:29:48] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[24.06 20:29:48] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[24.06 20:29:48] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
[24.06 20:29:48] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
[24.06 20:29:48] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
[24.06 20:29:48] [Server] Caused byjava.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
[24.06 20:29:48] [Server] 	at com.cyanogen.experienceobelisk.block.ModBlocksInit.<clinit>(ModBlocksInit.java:30) ~[experienceobelisk-v1.4.4-1.19.2.jar%23676!/:1.4.4-1.19.{re:classloading}
[24.06 20:29:48] [Server] 	at com.cyanogen.experienceobelisk.ExperienceObelisk.<init>(ExperienceObelisk.java:39) ~[experienceobelisk-v1.4.4-1.19.2.jar%23676!/:1.4.4-1.19.{re:classloading}
[24.06 20:29:48] [Server] 	... more
[24.06 20:29:48] [Server] Caused byjava.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
[24.06 20:29:48] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.2.14.jar%2367!/:1.{}
[24.06 20:29:48] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}

**Comment by LegitGamer1017** [comment]
I am here to report the same crash on my dedicated server. 

[crash-2023-06-26_20.22.04-fml.txt](https://github.com/terrarium-earth/Experience-Obelisk/files/11876313/crash-2023-06-26_20.22.04-fml.txt)

**Comment by edukny94** [comment]
[crash-2023-06-27_04.09.06-fml.txt](https://github.com/terrarium-earth/Experience-Obelisk/files/11876979/crash-2023-06-27_04.09.06-fml.txt)

Another crash on my dedicated server.

**Comment by cyanog3n** [comment]
Sorry about that! Fixed version currently being uploaded to cf and modrinth

**Comment by katubug** [comment]
Thanks so much!
